// Code generated by github.com/mohuishou/gen-const-msg DO NOT EDIT

// Package errors const code comment msg
package errors

// noErrorMsg if code is not found, GetMsg will return this
const noErrorMsg = "unknown error"

// messages get msg from const comment
var messages = map[StatusError]string{

	BadRequest:          "// 请求参数错误",
	Conflict:            "// 状态冲突",
	Forbidden:           "// 禁止访问",
	InternalServerError: "// 内部处理错误",
	NotFound:            "// 资源未找到",
	Unauthorized:        "// 未授权",
}

// String return string
func (code StatusError) String() string {
	return GetMsg(code)
}

// GetMsg get error msg
func GetMsg(code StatusError) string {
	var (
		msg string
		ok  bool
	)
	if msg, ok = messages[code]; !ok {
		msg = noErrorMsg
	}
	return msg
}
